name: "actual"

services:
  actual:
    image: "docker.io/actualbudget/actual-server:26.8.1-alpine"
    restart: "unless-stopped"
    environment:
      # See all options and more details at https://actualbudget.org/docs/config/
       - "ACTUAL_PORT=5006"
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - "actual:/data"
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: "60s"
      timeout: "10s"
      retries: "3"
      start_period: "20s"
    networks:
      - "shared"
    ports:
      - "5006:5006" # Expose port 5006 to the host for cron-based syncs
    expose:
     - "5006"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`actual.tqid.dev`)"
      - "traefik.http.routers.actual.entrypoints=web"

volumes:
  actual:

networks:
  default:
  shared:
    name: docker_default
    external: true
