name: "portainer"

services:
  portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce:2.44.0-alpine"
    restart: "unless-stopped"
    environment:
      TRUSTED_ORIGINS: "https://portainer.tqid.dev"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.tqid.dev`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=web"
    expose:
      - "9000"
      - "9443"
#      - "8000" # Remove if you do not intend to use Edge Agents
    networks:
      - default
      - shared

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
  shared:
    name: docker_default
    external: true
