name: "Files"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/files.yml
      - docker/files.yml
    branches:
      - main

jobs:
  safe:
    runs-on: self-hosted
    env:
      CONFIG_FOLDER: "/mnt/unitek/config"
      FILES_FOLDER: "/mnt/unitek/files"
    steps:
      - uses: actions/checkout@v7
      - run: docker compose -f docker/files.yml up --wait