name: "Pihole"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/pihole.yml
      - docker/pihole.yml
    branches:
      - main

jobs:
  pihole:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - run: docker compose -f docker/pihole.yml up --wait
