name: "Traefik"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/traefik.yml
      - docker/traefik.yml
    branches:
      - main

jobs:
  traefik:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - run: docker compose -f docker/traefik.yml up --wait
